language: python
python:
#  - "2.7"
#  - "3.4"
#  - "3.5"
#  - "3.6"      # current default Python on Travis CI
  - "3.7"
#  - "3.8"
#  - "3.9"
#  - "3.9-dev"  # 3.9 development branch
#  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install virtualenv -U
  - virtualenv venv
  - source venv/bin/activate
  - venv/bin/pip install -r requirements.txt
# command to run tests
script:
  - pytest pytest.py